# assumes ubuntu 18 host
- hosts: all
  handlers:
    - name: restart-systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
    - name: restart-nginx
      service:
        name: nginx
        state: restarted
    - name: restart-turnserver
      service:
        name: coturn
        state: restarted
  tasks:
    - name: set hostname
      hostname:
        name: "{{inventory_hostname_short}}"

    - name: Set timezone to New York, New York, the city so nice they named it twice
      timezone:
        name: America/New_York

    - name: setup etc hosts
      template: src=etc_hosts dest=/etc/hosts

    - name: setup resolv.conf
      template: src=resolved.conf dest=/etc/systemd/resolved.conf
      notify:
        - restart-systemd-resolved

    - name: Configure signing key for Jitsi repository.
      apt_key:
        id: 66A9CD0595D6AFA247290D3BEF8B479E2DC1389C
        url: "https://download.jitsi.org/jitsi-key.gpg.key"
        state: present

    - name: Install Jitsi apt repo.
      apt_repository:
        repo: "deb https://download.jitsi.org/ stable/"
        state: "present"
        # Ansible will automatically add the ".list" suffix.
        filename: /etc/apt/sources.list.d/jitsi_meet

    # need to set missing config parameters
    # then run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

    - name: Set debconf hostname jitsi-meet.
      debconf:
        name: "jitsi-videobridge"
        question: "jitsi-videobridge/jvb-hostname"
        value: "{{ inventory_hostname }}"
        vtype: "string"
#      notify:
#        - restart jitsi-videobridge
#        - restart jicofo
#        - restart prosody

    - name: Set debconf certoption jitsi-meet.
      debconf:
        name: "jitsi-meet"
        question: "jitsi-meet/cert-choice"
        value: "Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)"
        vtype: "string"
#      notify:
#        - restart jitsi-videobridge
#        - restart jicofo
#        - restart prosody

    - name: Install Jitsi Meet
      apt:
        name: jitsi-meet
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: setup letsencrypt
      include: letsencrypt.yml

    - name: copy in updated ngnix config with cert paths
      template: 
        src: jitsi-nginx.conf 
        dest: "/etc/nginx/sites-available/{{ inventory_hostname}}.conf"
      notify:
        - restart-nginx

    - name: copy in turnserver config
      template:
        src: turnserver.conf
        dest: /etc/turnserver.conf
      notify:
        - restart-turnserver
